[package]
name = "thrust"
version = "0.0.0"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]

[dependencies]
clap = "*"
log = "*"
rust-htslib = "*"
simple_logger = "*"

[dependencies.bio]
version = "*"
features = ["simd-accel"]  # This should speed up Occ queries

[profile.release]
lto = true
