[package]
name = "mapad"
version = "0.0.30-alpha.0"
description = "An aDNA aware short-read mapper"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]
edition = "2018"
readme = "Readme.md"
publish = false

[dependencies]
clap = "2.33.3"
log = "0.4.14"
rust-htslib = { git = "https://github.com/jch-13/rust-htslib.git", branch = "aux/rewrite", default-features = false}
simple_logger = "1.11.0"
bincode = "1.3.2"
bio = { version = "0.32.0", features = ["runtime-dispatch-simd"] }
assert_approx_eq = "1.1.0"
smallvec = "1.6.1"
rand = "0.8.3"
serde = { version = "1.0.124", features = ["derive"] }
snap = "1.0.4"
either = "1.6.1"
rayon = "1.5.0"
mio = { version = "0.7.10", features = ["os-poll", "tcp"] }
enum_dispatch = "0.3.5"
min-max-heap = { git = "https://github.com/jch-13/min-max-heap-rs.git", branch = "PRs"}
slab = "0.4.2"

[dev-dependencies]
criterion = "0.3.4"
tempfile = "3.2.0"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.bench]
lto = "fat"
codegen-units = 1
