[package]
name = "thrust"
version = "0.0.1"
description = "An aDNA aware short-read mapper"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]
edition = "2018"
readme = "Readme.md"

[features]
avx-accel = ["bio/avx-accel"]
simd-accel = ["bio/simd-accel"]

[dependencies]
clap = "2.33.0"
log = "0.4.6"
rust-htslib = "0.24.0"
simple_logger = "1.3.0"
bincode = "1.1.4"
bio = { git = "https://vcs.eva.mpg.de/christian_heide/rust-bio", branch = "biinterval_pub" }
assert_approx_eq = "1.1.0"
smallvec = "0.6.10"
rand = "0.7.0"
serde = { version = "1.0.94", features = ["derive"] }
snap = "0.2.5"
either = "1.5.2"
rayon = "1.1.0"

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = true
