[package]
name = "mapad"
version = "0.0.24-alpha.0"
description = "An aDNA aware short-read mapper"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]
edition = "2018"
readme = "Readme.md"
publish = false

[dependencies]
clap = "2.33.1"
log = "0.4.8"
rust-htslib = { git = "https://vcs.eva.mpg.de/christian_heide/rust-htslib.git", branch = "feature/get_all_bam_tags" }
simple_logger = "1.6.0"
bincode = "1.2.1"
bio = { version = "0.30.1", features = ["runtime-dispatch-simd"] }
assert_approx_eq = "1.1.0"
smallvec = "1.4.0"
rand = "0.7.3"
serde = { version = "1.0.110", features = ["derive"] }
snap = "1.0.0"
either = "1.5.3"
rayon = "1.3.0"
mio = { version = "0.7.0", features = ["os-poll", "tcp"] }
enum_dispatch = "0.3.0"
min-max-heap = "1.3.0"
slab = "0.4.2"

[dev-dependencies]
criterion = "0.3.2"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.bench]
lto = "fat"
codegen-units = 1

