[package]
name = "thrust"
version = "0.0.0"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]

[dependencies]
clap = "*"
log = "*"
rust-htslib = "*"
simple_logger = "*"
bincode = "*"

[dependencies.bio]
version = "0.22.1-alpha.0"
features = ["simd-accel"]  # This should speed up Occ queries

[patch.crates-io]
bio = { path = "../rust-bio" }

[profile.release]
lto = true
