[package]
name = "mapad"
version = "0.0.19-alpha.0"
description = "An aDNA aware short-read mapper"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]
edition = "2018"
readme = "Readme.md"
publish = false

[dependencies]
clap = "2.33.0"
log = "0.4.8"
rust-htslib = { git = "https://vcs.eva.mpg.de/christian_heide/rust-htslib.git", branch = "feature/get_all_bam_tags" }
simple_logger = "1.5.0"
bincode = "1.2.1"
bio = { git = "https://vcs.eva.mpg.de/christian_heide/rust-bio", branch = "biinterval_pub", features = ["runtime-dispatch-simd"] }
assert_approx_eq = "1.1.0"
smallvec = "1.2.0"
rand = "0.7.3"
serde = { version = "1.0.104", features = ["derive"] }
snap = "1.0.0"
either = "1.5.3"
rayon = "1.3.0"
mio = "0.6.21"
enum_dispatch = "0.2.1"
min-max-heap = "1.3.0"
backtrack-tree = { git = "https://vcs.eva.mpg.de/christian_heide/backtrack-tree" }

[dev-dependencies]
criterion = "=0.3.0"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.bench]
lto = "fat"
codegen-units = 1
