[package]
name = "thrust"
version = "0.0.0"
description = "An aDNA aware short-read mapper"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]
edition = "2018"

[features]
avx-accel = ["bio/avx-accel"]
simd-accel = ["bio/simd-accel"]

[dependencies]
clap = "*"
log = "*"
rust-htslib = "*"
simple_logger = "*"
bincode = "*"
bio = { git = "https://vcs.eva.mpg.de/christian_heide/rust-bio", branch = "biinterval_pub" }
libflate = "*"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = true
