[package]
name = "thrust"
version = "0.0.0"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]

[features]
avx-accel = ["bio/avx-accel"]
simd-accel = ["bio/simd-accel"]

[dependencies]
clap = "*"
log = "*"
rust-htslib = "*"
simple_logger = "*"
bincode = "*"
bio = "0.22.1-alpha.0"

[patch.crates-io]
bio = { path = "../rust-bio" }

[profile.release]
lto = true
