[package]
name = "mapad"
version = "0.0.38-alpha.0"
description = "An aDNA aware short-read mapper"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]
edition = "2021"
readme = "Readme.md"
publish = false
rust-version = "1.59"

[dependencies]
clap = { version = "3.1", features = ["cargo"] }
log = "0.4.14"
simple_logger = "2.1.0"
bincode = "1.3.3"
bio = { git = "https://github.com/jch-13/rust-bio.git", branch = "occ_small_k", features = ["runtime-dispatch-simd"] }
assert_approx_eq = "1.1.0"
smallvec = "1.8.0"
rand = "0.8.4"
serde = { version = "1.0.134", features = ["derive"] }
snap = "1.0.5"
either = "1.6.1"
rayon = "1.5.1"
mio = { version = "0.8.0", features = ["os-poll", "net"] }
min-max-heap = { git = "https://github.com/tov/min-max-heap-rs", branch = "master"}
slab = "0.4.5"
anyhow = "1.0.52"
fxhash = "0.2.1"
mimalloc = { version = "0.1.28", default-features = false }
noodles = { version = "0.22.0", features = ["bam", "sam", "core"] }
time = { version = "0.3.9", features = ["local-offset"] }

[dev-dependencies]
criterion = "0.3.5"
tempfile = "3.3.0"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.bench]
lto = "fat"
codegen-units = 1
