[package]
name = "thrust"
version = "0.0.0"
description = "An aDNA aware short-read mapper"
authors = ["J. Christian Heide <christian_heide@eva.mpg.de>"]
edition = "2018"

[features]
avx-accel = ["bio/avx-accel"]
simd-accel = ["bio/simd-accel"]

[dependencies]
clap = "2.33.0"
log = "0.4.6"
rust-htslib = "0.23.0"
simple_logger = "1.2.0"
bincode = "1.1.3"
bio = { git = "https://vcs.eva.mpg.de/christian_heide/rust-bio", branch = "biinterval_pub" }
libflate = "0.1.22"
maplit = "1.0.1"
assert_approx_eq = "1.1.0"
smallvec = "0.6.9"
rand = "0.6.5"

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = true
